//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2ExWpf.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Var2DBEntities : DbContext
    {
        public Var2DBEntities()
            : base("name=Var2DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Status_Booking> Status_Booking { get; set; }
        public virtual DbSet<Status_Cleaning> Status_Cleaning { get; set; }
        public virtual DbSet<Сleaning> Сleaning { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
