//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2ExWpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int Booking_Id { get; set; }
        public System.DateTime Payment_date { get; set; }
        public string Amount { get; set; }
        public int Payment_type_Id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
    }
}
