//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2ExWpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сleaning
    {
        public int Id { get; set; }
        public int Room_Id { get; set; }
        public int Staff_Id { get; set; }
        public System.DateTime Cleaning_date { get; set; }
        public int Status_Cleaning_Id { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status_Cleaning Status_Cleaning { get; set; }
    }
}
